[project]
name = "polydispute"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "awswrangler>=3.16.1",
    "boto3>=1.43.18",
    "dacite>=1.9.2",
    "fastapi>=0.136.3",
    "loguru>=0.7.3",
    "pandas>=3.0.3",
    "pmxt>=2.23.0",
    "polars>=1.39.3",
    "pydantic>=2.12.5",
    "python-dotenv>=1.2.2",
    "requests>=2.33.1",
    "sentry-sdk[fastapi]>=2.0.0",
    "tqdm>=4.67.3",
    "uvicorn>=0.48.0",
    "web3>=7.15.0",
]
